services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8080"
      - "--tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans"
      - "--accessLog=true"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend

  config-service:
    image: config-service:latest
    build:
      context: ./config
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      SERVER_PORT: 8888
      SPRING_APPLICATION_NAME: config-service
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/robinlafontaine/ecommerce-config.git
    healthcheck:
        test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.config.entrypoints=web"
      - "traefik.http.services.config.loadbalancer.server.port=8888"
      - "traefik.http.routers.config.middlewares="

  auth-service:
    image: auth-service:latest
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - backend
#    deploy:    # Uncomment to deploy in swarm mode
#      replicas: 2
    depends_on:
      config-service:
        condition: service_healthy
      auth-postgres:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_APPLICATION_NAME: auth-service
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unprotected.rule=Path(`/auth/authenticate`)"
      - "traefik.http.routers.unprotected.entrypoints=web"
      - "traefik.http.routers.unprotected.service=unprotected"
      - "traefik.http.services.unprotected.loadbalancer.server.port=8082"
      - "traefik.http.routers.unprotected.middlewares="
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.service=auth"
      - "traefik.http.services.auth.loadbalancer.server.port=8082"
      - "traefik.http.routers.auth.middlewares=jwt-auth"
      - "traefik.http.middlewares.jwt-auth.forwardauth.address=http://auth-service:8082/auth/validate"
      - "traefik.http.middlewares.jwt-auth.forwardauth.authRequestHeaders=Authorization, X-Forwarded-Uri"
      - "traefik.http.middlewares.jwt-auth.forwardauth.trustforwardheader=true"

  inventory-service:
    image: inventory-service:latest
    build:
      context: ./inventory
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - ./images:/images
    depends_on:
      config-service:
        condition: service_healthy
      inventory-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      SERVER_PORT: 8083
      SPRING_APPLICATION_NAME: inventory-service
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventory.entrypoints=web"
      - "traefik.http.routers.inventory.rule=PathPrefix(`/inventory`)"
      - "traefik.http.services.inventory.loadbalancer.server.port=8083"
      - "traefik.http.routers.inventory.middlewares=jwt-auth"
      - "traefik.http.middlewares.jwt-auth.forwardauth.address=http://auth-service:8082/auth/validate"
      - "traefik.http.middlewares.jwt-auth.forwardauth.authRequestHeaders=Authorization, X-Forwarded-Uri"
      - "traefik.http.middlewares.jwt-auth.forwardauth.trustforwardheader=true"

  payment-service:
    image: payment-service:latest
    build:
      context: ./payment
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_healthy
      payment-postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8084
      SPRING_APPLICATION_NAME: payment-service
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.entrypoints=web"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payments`)"
      - "traefik.http.services.payment.loadbalancer.server.port=8084"
      - "traefik.http.routers.payment.middlewares=jwt-auth"
      - "traefik.http.middlewares.jwt-auth.forwardauth.address=http://auth-service:8082/auth/validate"
      - "traefik.http.middlewares.jwt-auth.forwardauth.authRequestHeaders=Authorization, X-Forwarded-Uri"
      - "traefik.http.middlewares.jwt-auth.forwardauth.trustforwardheader=true"

  order-service:
    image: order-service:latest
    build:
      context: ./order
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_healthy
      order-postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8085
      SPRING_APPLICATION_NAME: order-service
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.entrypoints=web"
      - "traefik.http.routers.order.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.order.loadbalancer.server.port=8085"
      - "traefik.http.routers.order.middlewares=jwt-auth"
      - "traefik.http.middlewares.jwt-auth.forwardauth.address=http://auth-service:8082/auth/validate"
      - "traefik.http.middlewares.jwt-auth.forwardauth.authRequestHeaders=Authorization, X-Forwarded-Uri"
      - "traefik.http.middlewares.jwt-auth.forwardauth.trustforwardheader=true"

  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/auth/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/auth_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=auth_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/inventory/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/inventory_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=inventory_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/payment/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/payment_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=payment_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/order/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/order_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=order_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: image_bucket
    command: server --address ':9000' --console-address ':9001' /data
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=PathPrefix(`/product-images`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.middlewares="

  zipkin:
    image: openzipkin/zipkin
    networks:
        - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zipkin.entrypoints=web"
      - "traefik.http.routers.zipkin.rule=PathPrefix(`/zipkin`)"
      - "traefik.http.services.zipkin.loadbalancer.server.port=9411"
      - "traefik.http.routers.zipkin.middlewares=jwt-auth"
      - "traefik.http.middlewares.jwt-auth.forwardauth.address=http://auth-service:8082/auth/validate"
      - "traefik.http.middlewares.jwt-auth.forwardauth.authRequestHeaders=Authorization, X-Forwarded-Uri"
      - "traefik.http.middlewares.jwt-auth.forwardauth.trustforwardheader=true"

networks:
  backend:
    driver: bridge



