spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://authentication-service:8082
          predicates:
            - Path=/authenticate
          filters:
            - RewritePath=/authenticate, /authenticate
  authentication:
    enabled: true
  server:
    port: 8080
